package se.kth.model.bo;

// Generated Nov 13, 2013 2:23:29 PM by Hibernate Tools 4.0.0

/**
 * PrivateMessage generated by hbm2java
 */
public class PrivateMessage implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer privateMessageId;
	private User userByToUser;
	private User userByFromUser;
	private String message;

	public PrivateMessage() {
	}

	public PrivateMessage(User userByToUser, User userByFromUser) {
		this.userByToUser = userByToUser;
		this.userByFromUser = userByFromUser;
	}

	public PrivateMessage(User userByToUser, User userByFromUser, String message) {
		this.userByToUser = userByToUser;
		this.userByFromUser = userByFromUser;
		this.message = message;
	}

	public Integer getPrivateMessageId() {
		return this.privateMessageId;
	}

	public void setPrivateMessageId(Integer privateMessageId) {
		this.privateMessageId = privateMessageId;
	}

	public User getUserByToUser() {
		return this.userByToUser;
	}

	public void setUserByToUser(User userByToUser) {
		this.userByToUser = userByToUser;
	}

	public User getUserByFromUser() {
		return this.userByFromUser;
	}

	public void setUserByFromUser(User userByFromUser) {
		this.userByFromUser = userByFromUser;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
