package se.kth.model.bo;

// Generated Nov 13, 2013 3:03:35 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PrivateMessage generated by hbm2java
 */
public class PrivateMessage implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int privateMessageId;
	private User userByToUser;
	private User userByFromUser;
	private String message;
	private Date messageSent;

	public PrivateMessage() {
	}

	public PrivateMessage(int privateMessageId, User userByToUser,
			User userByFromUser, Date messageSent) {
		this.privateMessageId = privateMessageId;
		this.userByToUser = userByToUser;
		this.userByFromUser = userByFromUser;
		this.messageSent = messageSent;
	}

	public PrivateMessage(int privateMessageId, User userByToUser,
			User userByFromUser, String message, Date messageSent) {
		this.privateMessageId = privateMessageId;
		this.userByToUser = userByToUser;
		this.userByFromUser = userByFromUser;
		this.message = message;
		this.messageSent = messageSent;
	}

	public int getPrivateMessageId() {
		return this.privateMessageId;
	}

	public void setPrivateMessageId(int privateMessageId) {
		this.privateMessageId = privateMessageId;
	}

	public User getUserByToUser() {
		return this.userByToUser;
	}

	public void setUserByToUser(User userByToUser) {
		this.userByToUser = userByToUser;
	}

	public User getUserByFromUser() {
		return this.userByFromUser;
	}

	public void setUserByFromUser(User userByFromUser) {
		this.userByFromUser = userByFromUser;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getMessageSent() {
		return this.messageSent;
	}

	public void setMessageSent(Date messageSent) {
		this.messageSent = messageSent;
	}

}
