package se.kth.model.bo;

// Generated Nov 13, 2013 2:23:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int userProfileId;
	private User user;
	private String firstName;
	private String surname;
	private String email;
	private Date dateOfBirth;

	public UserProfile() {
	}

	public UserProfile(User user) {
		this.user = user;
	}

	public UserProfile(User user, String firstName, String surname,
			String email, Date dateOfBirth) {
		this.user = user;
		this.firstName = firstName;
		this.surname = surname;
		this.email = email;
		this.dateOfBirth = dateOfBirth;
	}

	public int getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(int userProfileId) {
		this.userProfileId = userProfileId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

}
