package se.kth.model.bo;

// Generated Nov 13, 2013 2:23:29 PM by Hibernate Tools 4.0.0

/**
 * UserLogMessage generated by hbm2java
 */
public class UserLogMessage implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer userLogMessageId;
	private User user;
	private String message;

	public UserLogMessage() {
	}

	public UserLogMessage(User user) {
		this.user = user;
	}

	public UserLogMessage(User user, String message) {
		this.user = user;
		this.message = message;
	}

	public Integer getUserLogMessageId() {
		return this.userLogMessageId;
	}

	public void setUserLogMessageId(Integer userLogMessageId) {
		this.userLogMessageId = userLogMessageId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
